#!/usr/bin/env python3
"""Supplementary figure (Plotly): AlphaFold3 ipTM / pTM for the NTase-NTP-Mg2+ panel.

WHY MULTIPLE SEEDS
A single AF3 model per NTase x NTP-pair condition (as in Figure 4C) cannot separate small
differences between substrates from AF3-prediction noise (e.g. shared-MSA artifacts), and gives
no SD or statistics. This script therefore expects up to 5 independent AF3 seeds per condition
(see inputs/af3_server_jobs/, generated by generate_af3_jobs.py), each producing the AF3
server's default 5 diffusion samples -> up to 25 models per condition.

INPUT: af3_results/**/ntase_*/*_summary_confidences_*.json (AF3 server downloads, any depth).

Robust to PARTIAL data: results are being submitted across several AF3 server accounts/days
(see inputs/af3_server_jobs/README.md for why), so at any point some (protein, NTP-pair)
conditions may have 0-4 seeds instead of the full 5. This script finds whatever is under
af3_results/ (searched recursively, any subfolder depth/name), prints a coverage table so
it's clear what's done vs still pending, and skips groups/tests that don't have enough data
yet rather than crashing - safe to re-run after every new batch of results lands.

For each protein (Bacillus phage Bcp1 NTase YP_009031408 and its Erinnyis ello granulovirus
homolog YP_009091875) and each of the 10 unordered NTP pairs drawn from {ATP, GTP, CTP, UTP}
(all with 3 Mg2+ ions; the 6 ATP/GTP/UTP pairs from Figure 4C plus 4 pairs adding CTP, which
CD-NTases are documented to use - Govande et al 2021, Whiteley et al 2019), plots box + all
per-model points for ipTM and pTM, with the per-seed mean +/- SD overlaid (where >=1 seed is
available), and reports (using only groups/pairs with enough data so far):
  - a permutation test across the NTP-pair groups that have data (per protein), on the
    per-seed means (the seed is the independent replicate)
  - pairwise exact/Monte-Carlo permutation tests per protein (n seeds vs n seeds, both >=2),
    BH-FDR corrected, written to supplementary/AF3_confidence_scores_pairwise_stats.tsv
  - the Pearson correlation between phage and viral ipTM (and pTM), across whichever NTP
    pairs currently have data for both proteins, with a bootstrap CI

USAGE: python3 scripts/make_supp_figure.py   (needs numpy, plotly, kaleido for png/pdf/svg export)

Writes supplementary/AF3_confidence_scores.{html,png,pdf,svg},
supplementary/AF3_confidence_scores_caption.txt and
supplementary/AF3_confidence_scores_coverage.tsv (what's done vs pending)
"""
import os, re, glob, json, itertools, collections
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Searched recursively so it doesn't matter how deep/how named the unzip landed
# (af3_results/no_utp_ctp/..., af3_results/with_utp_ctp/af3_server_batch_1_partial/..., etc.)
OUT = os.path.join(REPO, "supplementary")
os.makedirs(OUT, exist_ok=True)

# PANEL_C_MODE=1: used by merge_active_site_into_figure.py's panel C to get a
# version without the title/omnibus-p annotations (too cluttered at that
# panel's size) -- writes Figure/panelC_AF3_confidence_scores.png instead of
# overwriting the full, fully-annotated standalone supplementary figure.
PANEL_C_MODE = os.environ.get("PANEL_C_MODE") == "1"

PROTEINS = ["yp_009031408", "yp_009091875"]
PROTEIN_LABEL = {"yp_009031408": "YP_009031408 (phage Bcp1)",
                  "yp_009091875": "YP_009091875 (E. ello granulovirus)"}
NTP_ORDER = ["atp", "gtp", "ctp", "utp"]
PAIRS = [f"{a}_{b}" for i, a in enumerate(NTP_ORDER) for b in NTP_ORDER[i:]]
PAIR_LABEL = {p: p.upper().replace("_", "-") for p in PAIRS}
_PALETTE = ["#4c72b0", "#55a868", "#c44e52", "#8172b2", "#ccb974",
            "#64b5cd", "#937860", "#da8bc3", "#8c8c8c", "#ccb974"]
COLOR = {p: _PALETTE[i % len(_PALETTE)] for i, p in enumerate(PAIRS)}
N_SEEDS_PLANNED = 5

NAME_RE = re.compile(
    r"ntase_(?P<protein>yp_\d+)_(?P<a>atp|gtp|ctp|utp)_(?P<b>atp|gtp|ctp|utp)_mg3_seed(?P<seed>\d+)(_\d+)?$"
)


def subseed(path):
    d = os.path.basename(os.path.dirname(path))
    m = NAME_RE.match(d)
    if not m:
        return None
    protein = m.group("protein")
    pair = "_".join(sorted([m.group("a"), m.group("b")], key=NTP_ORDER.index))
    return protein, pair, int(m.group("seed")), m.group(5)


# permodel[k][protein][pair] -> list of per-model scores (up to 25 = 5 seeds x 5 samples)
# perseed[k][protein][pair][seed] -> list of per-sample scores for that seed
permodel = {m: {p: collections.defaultdict(list) for p in PROTEINS} for m in ("iptm", "ptm")}
perseed = {m: {p: collections.defaultdict(lambda: collections.defaultdict(list)) for p in PROTEINS}
           for m in ("iptm", "ptm")}

n_found = 0
for sc in glob.glob(os.path.join(REPO, "af3_results", "**", "ntase_*", "*_summary_confidences_*.json"),
                     recursive=True):
    parsed = subseed(sc)
    if not parsed:
        continue
    protein, pair, seed, dup = parsed
    if dup:  # skip re-run duplicates (name ends in _2 etc.), duplicates would double-count a seed
        continue
    j = json.load(open(sc))
    n_found += 1
    for k in ("iptm", "ptm"):
        permodel[k][protein][pair].append(j[k])
        perseed[k][protein][pair][seed].append(j[k])

if n_found == 0:
    raise SystemExit(
        "No AF3 summary_confidences JSONs found under af3_results/ (searched recursively for "
        "ntase_*/*_summary_confidences_*.json).\nUnzip AlphaFold3 server results there first."
    )

perseed_mean = {
    k: {p: {pair: [float(np.mean(perseed[k][p][pair][sd])) for sd in sorted(perseed[k][p][pair])]
            for pair in PAIRS}
        for p in PROTEINS}
    for k in ("iptm", "ptm")
}

# ---------------- coverage ----------------
coverage_rows = []
print(f"Coverage (seeds found / {N_SEEDS_PLANNED} planned):\n")
header = f"  {'pair':9s} " + "".join(f"{PROTEIN_LABEL[p]:>28s}" for p in PROTEINS)
print(header)
n_complete = n_partial = n_missing = 0
for pair in PAIRS:
    row = f"  {PAIR_LABEL[pair]:9s} "
    for p in PROTEINS:
        n_seeds = len(perseed["iptm"][p][pair])
        n_models = len(permodel["iptm"][p][pair])
        status = "FULL" if n_seeds >= N_SEEDS_PLANNED else ("partial" if n_seeds > 0 else "MISSING")
        if n_seeds >= N_SEEDS_PLANNED:
            n_complete += 1
        elif n_seeds > 0:
            n_partial += 1
        else:
            n_missing += 1
        row += f"{n_seeds}/{N_SEEDS_PLANNED} seeds ({n_models:>2d} models, {status})".rjust(28)
        coverage_rows.append(dict(pair=pair, protein=p, n_seeds=n_seeds, n_models=n_models, status=status))
    print(row)
print(f"\n  {n_complete} complete, {n_partial} partial, {n_missing} not started "
      f"(of {len(PAIRS) * len(PROTEINS)} protein x pair conditions)\n")

with open(os.path.join(OUT, "AF3_confidence_scores_coverage.tsv"), "w") as fh:
    fh.write("pair\tprotein\tn_seeds\tn_seeds_planned\tn_models\tstatus\n")
    for r in coverage_rows:
        fh.write(f"{PAIR_LABEL[r['pair']]}\t{r['protein']}\t{r['n_seeds']}\t{N_SEEDS_PLANNED}\t"
                  f"{r['n_models']}\t{r['status']}\n")


def perm_p(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    obs = abs(a.mean() - b.mean())
    pool = np.concatenate([a, b]); na = len(a); hits = tot = 0
    for idx in itertools.combinations(range(len(pool)), na):
        mask = np.zeros(len(pool), bool); mask[list(idx)] = True
        hits += abs(pool[mask].mean() - pool[~mask].mean()) >= obs - 1e-12
        tot += 1
    return hits / tot


def perm_anova_p(groups, n_iter=20000, seed=0):
    """Exact-ish (Monte Carlo) permutation test for a one-way group effect on the means."""
    rng = np.random.default_rng(seed)
    arrs = [np.asarray(g, float) for g in groups]
    sizes = [len(g) for g in arrs]
    pooled = np.concatenate(arrs)
    grand = pooled.mean()

    def stat(vals_by_group):
        return sum(len(v) * (np.mean(v) - grand) ** 2 for v in vals_by_group)

    obs = stat(arrs)
    hits = 0
    idx = np.arange(len(pooled))
    for _ in range(n_iter):
        rng.shuffle(idx)
        shuffled = pooled[idx]
        cuts = np.cumsum(sizes)[:-1]
        parts = np.split(shuffled, cuts)
        hits += stat(parts) >= obs - 1e-12
    return hits / n_iter


def bh_fdr(pvals):
    if not pvals:
        return []
    order = np.argsort(pvals)
    ranked = np.asarray(pvals)[order]
    n = len(pvals)
    q = ranked * n / (np.arange(n) + 1)
    q = np.minimum.accumulate(q[::-1])[::-1]
    out = np.empty(n)
    out[order] = np.minimum(q, 1.0)
    return out


def stars(q):
    return "****" if q < 1e-4 else "***" if q < 1e-3 else "**" if q < 1e-2 else "*" if q < 5e-2 else "ns"


# ---------------- statistics (only over pairs/groups with enough data so far) ----------------
print("Per-condition ipTM/pTM: mean +/- SD (n = seeds, up to 5 samples/seed pooled per model list)\n")
group_kw_p = {}
pairwise_rows = []
MIN_SEEDS_FOR_PAIRWISE = 2  # need >=2 vs >=2 for a non-degenerate permutation test
for k in ("iptm", "ptm"):
    for p in PROTEINS:
        print(f"  {k.upper()} {PROTEIN_LABEL[p]}")
        pairs_with_data = [pair for pair in PAIRS if len(permodel[k][p][pair]) > 0]
        for pair in PAIRS:
            vals = permodel[k][p][pair]
            sm = perseed_mean[k][p][pair]
            if not vals:
                print(f"    {PAIR_LABEL[pair]:9s} no data yet")
                continue
            sd_str = f"{np.std(vals, ddof=1):.3f}" if len(vals) > 1 else "n/a (1 model)"
            print(f"    {PAIR_LABEL[pair]:9s} n_models={len(vals):2d}  "
                  f"mean={np.mean(vals):.3f} SD={sd_str}   "
                  f"per-seed means={[round(x,3) for x in sm]}")
        if len(pairs_with_data) >= 2:
            kw = perm_anova_p([perseed_mean[k][p][pair] for pair in pairs_with_data])
            group_kw_p[(k, p)] = kw
            print(f"    -> permutation test across the {len(pairs_with_data)}/{len(PAIRS)} NTP "
                  f"pairs with data so far: p={kw:.4f}\n")
        else:
            group_kw_p[(k, p)] = None
            print(f"    -> only {len(pairs_with_data)}/{len(PAIRS)} NTP pairs have data so far; "
                  "skipping the omnibus test until >=2 are available\n")
        # pairwise: two-sided exact permutation test on per-seed means; BH-FDR corrected
        # within the family of 45 NTP-pair comparisons for this (score, protein).
        raw = []
        for a, b in itertools.combinations(PAIRS, 2):
            sa, sb = perseed_mean[k][p][a], perseed_mean[k][p][b]
            na, nb = len(sa), len(sb)
            r = dict(score=k, protein=p, pair_a=a, pair_b=b, n_a=na, n_b=nb,
                     mean_a=float(np.mean(sa)) if sa else None,
                     mean_b=float(np.mean(sb)) if sb else None,
                     delta=(float(np.mean(sb) - np.mean(sa)) if sa and sb else None),
                     perm_p=None, fdr_q=None)
            if na < MIN_SEEDS_FOR_PAIRWISE or nb < MIN_SEEDS_FOR_PAIRWISE:
                pairwise_rows.append(r)
                continue
            r["perm_p"] = perm_p(sa, sb)
            raw.append(r)
        for r, q in zip(raw, bh_fdr([r["perm_p"] for r in raw])):
            r["fdr_q"] = q
            pairwise_rows.append(r)

# ---- pairwise results table (machine-readable TSV + human-readable Markdown) ----
# minimum attainable two-sided p for n vs n via exact permutation = 2 / C(2n, n)
_min_p = {n: 2.0 / len(list(itertools.combinations(range(2 * n), n))) for n in (2, 3, 4, 5)}
_fam = len(list(itertools.combinations(PAIRS, 2)))
with open(os.path.join(OUT, "AF3_confidence_scores_pairwise_stats.tsv"), "w") as fh:
    fh.write("score\tprotein\tpair_a\tpair_b\tn_seeds_a\tn_seeds_b\t"
             "mean_a\tmean_b\tdelta_b_minus_a\tperm_p_raw\tq_BH_FDR\tsignif_q_0.05\n")
    for r in pairwise_rows:
        f3 = lambda v: f"{v:.4f}" if v is not None else "NA"
        sig = "NA" if r["fdr_q"] is None else ("yes" if r["fdr_q"] < 0.05 else "no")
        fh.write(f"{r['score']}\t{r['protein']}\t{PAIR_LABEL[r['pair_a']]}\t{PAIR_LABEL[r['pair_b']]}\t"
                 f"{r['n_a']}\t{r['n_b']}\t{f3(r['mean_a'])}\t{f3(r['mean_b'])}\t{f3(r['delta'])}\t"
                 f"{f3(r['perm_p'])}\t{f3(r['fdr_q'])}\t{sig}\n")

with open(os.path.join(OUT, "AF3_confidence_scores_pairwise_stats.md"), "w") as fh:
    fh.write("# Pairwise NTP-pair comparisons of AlphaFold 3 confidence\n\n")
    fh.write(
        "Two-sided **exact permutation test** on the per-seed means (n = 5 independent AF3 "
        "seeds per group, the seed as the replicate). p-values are corrected for multiple "
        f"comparisons with the **Benjamini-Hochberg FDR** within each family of {_fam} NTP-pair "
        "comparisons (one family per protein x score). `delta` = mean(pair_b) - mean(pair_a) on "
        "the per-seed means. Bold rows are significant at BH-FDR q < 0.05.\n\n"
        f"Note: with 5 vs 5 seeds the smallest attainable raw p is 2/C(10,5) = {_min_p[5]:.4f}, "
        "so many strongly-separated pairs sit exactly at that floor; Bonferroni/Holm FWER "
        "correction is uninformative at this seed count, hence BH-FDR is reported.\n\n")
    for k, ylab in (("iptm", "ipTM"), ("ptm", "pTM")):
        for p in PROTEINS:
            fh.write(f"## {ylab} - {PROTEIN_LABEL[p]}\n\n")
            fh.write("| NTP pair A | NTP pair B | mean A | mean B | delta (B-A) | perm p (raw) | "
                     "q (BH-FDR) | signif. |\n")
            fh.write("|---|---|---|---|---|---|---|---|\n")
            rows = [r for r in pairwise_rows if r["score"] == k and r["protein"] == p]
            for r in sorted(rows, key=lambda r: (r["fdr_q"] is None, r["fdr_q"] if r["fdr_q"] is not None else 1)):
                if r["perm_p"] is None:
                    fh.write(f"| {PAIR_LABEL[r['pair_a']]} | {PAIR_LABEL[r['pair_b']]} | - | - | - | "
                             "NA (insufficient seeds) | NA | NA |\n")
                    continue
                sig = r["fdr_q"] < 0.05
                cells = [PAIR_LABEL[r["pair_a"]], PAIR_LABEL[r["pair_b"]],
                         f"{r['mean_a']:.3f}", f"{r['mean_b']:.3f}", f"{r['delta']:+.3f}",
                         f"{r['perm_p']:.4f}", f"{r['fdr_q']:.4f}", f"{stars(r['fdr_q'])}"]
                if sig:
                    cells = [f"**{c}**" for c in cells]
                fh.write("| " + " | ".join(cells) + " |\n")
            fh.write("\n")

# Pearson correlation between the two proteins, over NTP pairs where BOTH have >=1 model so far
corr_lines = []
for k in ("iptm", "ptm"):
    common_pairs = [pair for pair in PAIRS
                     if permodel[k]["yp_009031408"][pair] and permodel[k]["yp_009091875"][pair]]
    if len(common_pairs) < 3:
        line = (f"{k.upper()} phage-vs-viral Pearson r: not computed yet - only "
                 f"{len(common_pairs)}/{len(PAIRS)} NTP pairs have data for both proteins "
                 "(need >=3).")
        print(line)
        corr_lines.append(line)
        continue
    x = np.array([np.mean(permodel[k]["yp_009031408"][pair]) for pair in common_pairs])
    y = np.array([np.mean(permodel[k]["yp_009091875"][pair]) for pair in common_pairs])
    r = float(np.corrcoef(x, y)[0, 1])
    rng = np.random.default_rng(1)
    boots = []
    n = len(x)
    for _ in range(20000):
        idx = rng.integers(0, n, n)
        if np.std(x[idx]) == 0 or np.std(y[idx]) == 0:
            continue
        boots.append(np.corrcoef(x[idx], y[idx])[0, 1])
    lo, hi = np.percentile(boots, [2.5, 97.5]) if boots else (float("nan"), float("nan"))
    line = (f"{k.upper()} phage-vs-viral Pearson r={r:.3f} (bootstrap 95% CI [{lo:.3f}, {hi:.3f}], "
            f"n={len(common_pairs)}/{len(PAIRS)} NTP pairs with data for both proteins so far)")
    print(line)
    corr_lines.append(line)

# ---------------- figure ----------------
fig = make_subplots(rows=2, cols=2, horizontal_spacing=0.09, vertical_spacing=0.14,
                     subplot_titles=[PROTEIN_LABEL[p] for p in PROTEINS] * 1)
XPOS = {pair: i for i, pair in enumerate(PAIRS)}

for row, k, ylab in ((1, "iptm", "ipTM"), (2, "ptm", "pTM")):
    for col, p in enumerate(PROTEINS, start=1):
        for pair in PAIRS:
            y = permodel[k][p][pair]
            if not y:
                continue
            fig.add_trace(go.Violin(
                y=y, x=[PAIR_LABEL[pair]] * len(y), name=PAIR_LABEL[pair], showlegend=False,
                points="all", jitter=0.35, pointpos=0, width=0.85,
                box_visible=True, meanline_visible=len(y) > 1, scalemode="width", bandwidth=0.006,
                spanmode="hard",
                fillcolor=COLOR[pair] + "26",
                line=dict(color=COLOR[pair], width=1.2),
                marker=dict(color=COLOR[pair], size=3.5, opacity=0.55, line=dict(width=0)),
            ), row=row, col=col)
            sm = perseed_mean[k][p][pair]
            fig.add_trace(go.Scatter(
                x=[PAIR_LABEL[pair]], y=[np.mean(sm)],
                error_y=dict(type="data", array=[np.std(sm, ddof=1) if len(sm) > 1 else 0],
                             thickness=1.5, width=4, visible=len(sm) > 1),
                mode="markers", marker=dict(color="black", size=5, symbol="diamond"),
                showlegend=False,
            ), row=row, col=col)
        fig.update_yaxes(range=[0.7, 1.0], title_text=ylab if col == 1 else None,
                          gridcolor="rgba(0,0,0,0.08)", zeroline=False, row=row, col=col)
        kw = group_kw_p[(k, p)]
        kw_text = f"permutation p={kw:.3f}" if kw is not None else "permutation test pending (need >=2 pairs)"
        n_pairs_data = sum(1 for pair in PAIRS if permodel[k][p][pair])
        if not PANEL_C_MODE:
            fig.add_annotation(
                x=1, y=1.0, xref=f"x{'' if row==1 and col==1 else (col if row==1 else col+2)} domain",
                yref=f"y{'' if row==1 and col==1 else (col if row==1 else col+2)} domain",
                xanchor="right", yshift=-4, showarrow=False,
                text=f"omnibus {kw_text} ({n_pairs_data}/{len(PAIRS)} pairs so far)",
                font=dict(size=10, color="#444"), row=row, col=col)

fig.update_xaxes(categoryorder="array", categoryarray=[PAIR_LABEL[s] for s in PAIRS])
n_total = len(PAIRS) * len(PROTEINS)
n_done = sum(1 for k in ("iptm",) for p in PROTEINS for pair in PAIRS
             if len(perseed["iptm"][p][pair]) >= N_SEEDS_PLANNED)
title_suffix = (" - PRELIMINARY, in progress" if n_done < n_total else "")
layout_kwargs = dict(template="simple_white", width=980, height=760, violingap=0.25,
                      margin=dict(l=64, r=20, t=64, b=44), font=dict(size=12))
if PANEL_C_MODE:
    layout_kwargs["margin"] = dict(l=64, r=20, t=20, b=44)  # no title -> reclaim top margin
else:
    layout_kwargs["title"] = dict(
        text="NTase-NTP(pair)-3xMg2+ AlphaFold 3 confidence "
             f"(up to 5 seeds x 5 samples per condition){title_suffix}",
        font=dict(size=13), x=0.5, xanchor="center", y=0.99)
fig.update_layout(**layout_kwargs)

if PANEL_C_MODE:
    out_png = os.path.join(REPO, "Figure", "panelC_AF3_confidence_scores.png")
    os.makedirs(os.path.dirname(out_png), exist_ok=True)
    fig.write_image(out_png, scale=3)
    print(f"wrote {out_png}")
else:
    fig.write_html(os.path.join(OUT, "AF3_confidence_scores.html"), include_plotlyjs="cdn")
    for ext in ("png", "pdf", "svg"):
        fig.write_image(os.path.join(OUT, f"AF3_confidence_scores.{ext}"), scale=3)

n_pairwise_computed = sum(1 for r in pairwise_rows if r["perm_p"] is not None)
cap = (
    "Supplementary Figure. AlphaFold 3 confidence for NTase-NTP(pair)-Mg2+ co-folding, with "
    "up to five independent AlphaFold 3 seeds (five diffusion samples each, up to 25 models "
    "per condition) per NTase per NTP pair"
    + (f" - PRELIMINARY: only {n_done}/{n_total} protein x NTP-pair conditions have the full "
       "5 seeds so far, see AF3_confidence_scores_coverage.tsv; the rest are being submitted "
       "incrementally." if n_done < n_total else ".")
    + " Rows: (top) ipTM, (bottom) pTM. Columns: Bacillus phage Bcp1 NTase "
    "(YP_009031408) and its homolog from Erinnyis ello granulovirus (YP_009091875). Each NTase "
    f"was co-folded with one of {len(PAIRS)} unordered NTP pairs drawn from "
    "{ATP, GTP, CTP, UTP} and three Mg2+ ions. Points: every model available so far; box: "
    "median and interquartile range; black diamond with error bar: per-seed mean +/- SD (n = "
    "seeds available). Annotated omnibus p-value: permutation test for any difference among the "
    "NTP-pair groups with data so far (per-seed means, the seed as the independent replicate). "
    "All pairwise NTP-pair comparisons (two-sided exact permutation test on the per-seed means, "
    "Benjamini-Hochberg FDR-corrected within each family of "
    f"{len(list(itertools.combinations(PAIRS, 2)))} comparisons per protein per score) are "
    "reported in AF3_confidence_scores_pairwise_stats.tsv (machine-readable) and "
    "AF3_confidence_scores_pairwise_stats.md (formatted, sorted by q).\n\n"
    + "\n".join(corr_lines) + "\n\n"
    f"{n_pairwise_computed} of {len(pairwise_rows)} possible pairwise NTP-pair comparisons per "
    "protein per score have enough data (exact permutation test on per-seed means, both groups "
    "n>=2, Benjamini-Hochberg FDR corrected); all rows, including not-yet-computable ones, are "
    "in AF3_confidence_scores_pairwise_stats.tsv."
)
open(os.path.join(OUT, "AF3_confidence_scores_caption.txt"), "w").write(cap + "\n")
print("\nwrote supplementary/AF3_confidence_scores.{html,png,pdf,svg}, _caption.txt, "
      "_pairwise_stats.tsv and _coverage.tsv")
